### ISSUE TITLE
Warnings after installation

### ISSUE THREAD

**Issue by h1ps** [arkuuu/publin#22] opened 2016-09-23 19:37 UTC
Hi, i get a lot of warnings after i installed these version of publin.

For example in **browse → Authors** 
_url: publin/?p=browse&by=author_

`Warning: Declaration of publin\src\AuthorRepository::select() should be compatible with publin\src\Repository::select($table, array $columns = NULL) in \htdocs\publin\src\AuthorRepository.php on line 11`

`Warning: Declaration of publin\src\AuthorRepository::order($column, $order) should be compatible with publin\src\Repository::order($column, $order, $table = 'self') in \htdocs\publin\src\AuthorRepository.php on line 11`

`Warning: Declaration of publin\src\AuthorRepository::where($column, $comparator, $value, $function = NULL) should be compatible with publin\src\Repository::where($column, $comparator, $value, $function = NULL, $table = 'self') in \htdocs\publin\src\AuthorRepository.php on line 11`

or if i try to view some **author** i get the following warnings.
_url: publin/?p=author&id=1_

`Warning: scandir(/publin/src/indices/implementations,/publin/src/indices/implementations): Das System kann den angegebenen Pfad nicht finden. (code: 3) in \htdocs\publin\src\indices\IndexFactory.php on line 75`

`Warning: scandir(/publin/src/indices/implementations): failed to open dir: No such file or directory in \htdocs\publin\src\indices\IndexFactory.php on line 75`

`Warning: scandir(): (errno 2): No such file or directory in \htdocs\publin\src\indices\IndexFactory.php on line 75`

`Warning: Invalid argument supplied for foreach() in \htdocs\publin\src\indices\IndexFactory.php on line 76`

`Warning: Declaration of publin\src\AuthorRepository::select() should be compatible with publin\src\Repository::select($table, array $columns = NULL) in \htdocs\publin\src\AuthorRepository.php on line 11`

`Warning: Declaration of publin\src\AuthorRepository::order($column, $order) should be compatible with publin\src\Repository::order($column, $order, $table = 'self') in \htdocs\publin\src\AuthorRepository.php on line 11`

`Warning: Declaration of publin\src\AuthorRepository::where($column, $comparator, $value, $function = NULL) should be compatible with publin\src\Repository::where($column, $comparator, $value, $function = NULL, $table = 'self') in \htdocs\publin\src\AuthorRepository.php on line 11`

`Warning: Declaration of publin\src\PublicationRepository::select() should be compatible with publin\src\Repository::select($table, array $columns = NULL) in \htdocs\publin\src\PublicationRepository.php on line 126`

`Warning: Declaration of publin\src\PublicationRepository::where($column, $comparator, $value, $function = NULL) should be compatible with publin\src\Repository::where($column, $comparator, $value, $function = NULL, $table = 'self') in \htdocs\publin\src\PublicationRepository.php on line 126`

`Warning: Declaration of publin\src\FileRepository::select() should be compatible with publin\src\Repository::select($table, array $columns = NULL) in \htdocs\publin\src\FileRepository.php on line 53`

`Warning: Declaration of publin\src\UrlRepository::select() should be compatible with publin\src\Repository::select($table, array $columns = NULL) in \htdocs\publin\src\UrlRepository.php on line 53`

**Comment by arkuuu** [comment] 2016-10-05 05:33
Sorry for the late reply!

Are you using PHP7? That would explain most of the "Declaration of ..." warnings.
I will look into this as soon as I can. Meanwhile, you could try putting this hack into the `index.php` just above `spl_autoload_register`:

``` php
if (PHP_MAJOR_VERSION >= 7) {
    set_error_handler(function ($errno, $errstr) {
       return strpos($errstr, 'Declaration of') === 0;
    }, E_WARNING);
}
```

(Source: http://stackoverflow.com/a/36196748)

For the other errors, could you please checkout if the path `publin/src/indices/implementations` exists on your server? Are you using Windows or Linux?

**Comment by sablebyte** [comment] 2016-10-05 13:36
As noted in the readme, Publin has as minimum requirements PHP 5.3.14 and MySQL 5.5.38. Due to this fact, the indices have been developed by using a system configuration with the above noted specifications. 

To make sure that it still works, I downloaded the current master branch, installed Publin and inserted some publications, authors and citations. The test showed that the indices function works without problems with different configurations (Windows and Linux, Apache 2.2 and 2.4, PHP 5.3, 5.4, 5.5 and 5.6).  I was not able to test it with PHP 7, since I have not installed PHP 7 on my system. So it still might be possible that there are problems when running Publin together with PHP 7.

PHP 7 has a lot of backwards incompatibilities (see [this list](http://php.net/manual/en/migration70.incompatible.php) for a rough overview). In general, this can produce a huge challenge to keep the code working both with PHP 5.3 and PHP 7. Of course, in an individual case this could be easier. But if this also applies to Publin is something which is still to be investigated.

If it is really the case that Publin does not work correctly with PHP 7 and if there is no easy solution to keep Publin working both with PHP 5.3 and PHP 7, there could be either the solution to raise the system requirements to PHP 7 or to clarify in the readme that Publin is currently not compatible with PHP 7. In my opinion, raising the system requirements would only be an option when PHP 7 is used by enough people. According to [these statistics](https://w3techs.com/technologies/details/pl-php/all/all), this seems not to be the case at the moment.

Before further investigating if Publin has some problems with PHP 7, @h1ps should make sure he has indicated the full path in the **ROOT_PATH** constant in the configuration file **config/Config.php** of Publin. In my case, the full path is **C:/Program Files (x86)/wamp/www/publin/**. Not using the full path may cause problems when the system tries to load the different indices. Indicating the full path might at least remove the error messages related to the indices.

**Comment by arkuuu** [comment] 2016-10-05 17:55
I was able to reproduce the following error(s):

```
PHP Warning:  scandir(): (errno 2): No such file or directory in .../publin/src/indices/IndexFactory.php on line 75
PHP Warning:  Invalid argument supplied for foreach() in .../publin/src/indices/IndexFactory.php on line 76
```

It was caused by an incorrect `ROOT_PATH` in `config/Config.php`, just as @sablebyte mentioned.
It may be misleading that the config template has `ROOT_PATH = '/'` set as default, **but you need to set it to the full absolut path to your publin installation.**

Regarding the other errors:

```
Warning: Declaration of publin\src\FileRepository::select() should be compatible with publin\src\Repository::select($table, array $columns = NULL) in \htdocs\publin\src\FileRepository.php on line 53
```

They must be caused by using PHP 7 because these warnings used to be `E_STRICT` errors before. In PHP 7 they've changed it to warnings. I have a fix for this ready and I am testing it right now.  You can expect it later today or tomorrow. **Please note that this does _not_ mean that Publin is fully PHP 7 compatible.**

**Closed as completed** 2016-10-05 19:33 UTC
Labels: bug
